#!/bin/sh
#
# Test aspell dictionary with wrong UTF-8 de_DE-1901 words.
#
# (c) 2018 Roland Rosenfeld <roland@debian.org>

TESTSDIR=$(dirname $0)

if [ -z "$AUTOPKGTEST_TMP" ]; then
    AUTOPKGTEST_TMP=$(mktemp -d)
fi
trap "rm -rf $AUTOPKGTEST_TMP" EXIT

aspell list -d de_DE-1901 < $TESTSDIR/typo.utf8.txt \
                       > $AUTOPKGTEST_TMP/aspell.typo.out

if diff $AUTOPKGTEST_TMP/aspell.typo.out $TESTSDIR/typo.utf8.txt > $AUTOPKGTEST_TMP/diff.typo.out
then
    exit 0
else
    echo "following words are wrongly accepted:"
    grep '^>' $AUTOPKGTEST_TMP/diff.typo.out
    exit 1
fi
