#!/bin/sh
#
# Test with wrong UTF-8 German words.
#
# (c) 2020 Roland Rosenfeld <roland@debian.org>

TESTSDIR=$(dirname $0)

if [ -z "$AUTOPKGTEST_TMP" ]; then
    AUTOPKGTEST_TMP=$(mktemp -d)
fi
trap "rm -rf $AUTOPKGTEST_TMP" EXIT

ispell -l -w 'äöüßÄÖÜ' -Tutf8 -d ogerman < $TESTSDIR/typo.utf8.txt \
                                         > $AUTOPKGTEST_TMP/ispell.typo.out

if diff $AUTOPKGTEST_TMP/ispell.typo.out $TESTSDIR/typo.utf8.txt \
	> $AUTOPKGTEST_TMP/diff.typo.out
then
    exit 0
else
    echo "following words are wrongly accepted:"
    grep '^>' $AUTOPKGTEST_TMP/diff.typo.out
    exit 1
fi
