#!/bin/sh
#
# Test with wrong ISO-8859-1 (Latin1) German words.
#
# (c) 2018 Roland Rosenfeld <roland@debian.org>

TESTSDIR=$(dirname $0)

if [ -z "$AUTOPKGTEST_TMP" ]; then
    AUTOPKGTEST_TMP=$(mktemp -d)
fi
trap "rm -rf $AUTOPKGTEST_TMP" EXIT

iconv -f UTF-8 -t ISO-8859-1 < $TESTSDIR/typo.utf8.txt > $AUTOPKGTEST_TMP/typo.latin1.txt

ispell -l -w 'äöüßÄÖÜ' -Tlatin1 -d ogerman < $AUTOPKGTEST_TMP/typo.latin1.txt \
                                           > $AUTOPKGTEST_TMP/ispell.typo.out

if diff $AUTOPKGTEST_TMP/ispell.typo.out $AUTOPKGTEST_TMP/typo.latin1.txt > $AUTOPKGTEST_TMP/diff.typo.out
then
    exit 0
else
    echo "following words are wrongly accepted:"
    grep '^>' $AUTOPKGTEST_TMP/diff.typo.out
    exit 1
fi
