#!/bin/sh
#
# Test, that "daß" exists in wordlist bug "dass" does not.
#
# (c) 2018 Roland Rosenfeld <roland@debian.org>

WLIST=/usr/share/dict/ogerman
if ! grep -q '^daß$' $WLIST
then
    echo "'daß' missing in wordlist"
    exit 1
fi
if grep -q '^dass$' $WLIST
then
    echo "'dass' should not be in wordlist (no German spelling)"
    exit 1
fi
